### ISSUE TITLE
call.php hard codes SIP/ for the extension

### ISSUE THREAD

**Issue by lgaetz** [Jolt1/Jolt-Select-Dial-PBX#2]
line 11: `$strChannel = "SIP/".$ext;`
assumes that the extension you wish to bridge is SIP, but later versions of Asterisk have PJSIP and all versions permit IAX, DAHDI and LOCAL.  I suggest adding a check to see if $ext `is_numeric` and then prepending SIP/ otherwise allow the user to set whatever extension they want.

There will probably be a problem passing a `/` character via URL, perhaps urlencoding/decoding the ext.

**Comment by Jolt1** [comment]
For my current needs this works but that's why this script is open sourced so everyone can modify to their needs... If you want the make the suggested changes i will review...

**Comment by lgaetz** [comment]
I have done a major rework of the file call.php and uploaded it as freepbx_call.php here:
https://github.com/lgaetz/Jolt-Select-Dial-PBX

Not sure if you are interested or not. My version requires FreePBX 2.9 or higher and would not work on plain Asterisk systems. It also must be installed on the same system as FreePBX. The plusses include:  fixing the issue raised in this ticket, and it provides an element of security in that it will only allow registered FreePBX extension numbers to originate calls. It is also zero config, no requirement for editing for AMI credentials.

**Comment by Jolt1** [comment]
I tested your script and it did not actually work for me...
I'm on 2.11.

**Comment by lgaetz** [comment]
Worked fine for me on my dev system running Asterisk 11, but testing on a 1.8 system is giving issues. I also found another potential issue of voicemail intercepting the first leg of the call. I will tinker some more.
